### ISSUE TITLE
Parsing unb segment 

### ISSUE THREAD

**Issue by tomjakobs1** [Chemaclass/edifact-parser#32]
Need example how to parse unb segment. 
Thank you

**Comment by Chemaclass** [comment]
Hi, @tomjakobs1! UNB were not supported yet, so I created a PR for that. Would this be enough for you? https://github.com/Chemaclass/edifact-parser/pull/33 Because UNB are global interchange structure ([source](https://unece.org/fileadmin/DAM/trade/edifact/untdid/d422_s.htm#structures))
<img width="471" alt="Screenshot 2023-02-09 at 21 39 50" src="https://user-images.githubusercontent.com/5256287/217933194-955e482b-d31a-4539-b090-45a7d3325976.png">

I thought it would be useful to have them on each message, so you can access to them any time. 
Look at the tests to see how you could use them: https://github.com/Chemaclass/edifact-parser/pull/33/files#diff-0cde6730d1c607101da4ad9f671f2b4ff0295860286620072fb003be354ed6dbR189

**Comment by tomjakobs1** [comment]
Hello @Chemaclass. That sounds like a good plan. Are you merging this into master ?

**Comment by tomjakobs1** [comment]
Or maybe the correct thing would do is to have the unb on the outside, since it is a header for all messages?

**Comment by tomjakobs1** [comment]
@Chemaclass  That sound to me like a good solution, and would probably make it more organized. Thank you so much for fantastic code and fast replies.

**Comment by tomjakobs1** [comment]
Btw are you still activliy adding to this project ? How about segments that is not in your segment list ? Can we add segments easily ? ie TSR  / GID, and so on ?

**Comment by Chemaclass** [comment]
>**Note**: the project is not abandoned, but I am not actively adding new stuff either.

I am not currently active on this project, but I can listen to ideas from other people, and (most especially) review PRs from others to add missing segments or anything that could help the UX or performance of the project. So, if you would like to have more segments you can fork the project and create a PR with them. (Multiple and small PRs are easier to review and merge). Also, if you need any help with that, you can always ask :)

**Comment by tomjakobs1** [comment]
That sound good. I havent collaborated on git projects before. But if i can help, i surely will

**Comment by Chemaclass** [comment]
@tomjakobs1 there you go ➡️  https://github.com/Chemaclass/edifact-parser/pull/34

**Comment by Chemaclass** [comment]
I created a new release supporting UNB and a separation between "global segments" and "transactional messages" https://github.com/Chemaclass/edifact-parser/releases/tag/5.0.0
